schemaVersion: 2.2.0
metadata:
  name: ansible-bastion-test.0.3
components:
  - name: tooling-container
    container:
      image: quay.io/jmeredit/bastiontest1:latest
      memoryRequest: 256M
      memoryLimit: 6Gi
      cpuRequest: 250m
      cpuLimit: 2000m
      args: ['tail', '-f', '/dev/null']  
