---
- name: Prepare
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:

    - name: 'Ensure test file is absent'
      ansible.builtin.file:
        path: "{{ test_role_file_dest }}"
        state: absent
