---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Example assertion
    ansible.builtin.stat:
      path: "/etc/motd"
    register: stat_output
  - name: Assert That Motd Exists
    ansible.builtin.assert:
      that: stat_output.stat.exists
