---
galaxy_info:
  author: Kathryn Yetter <kyetter@redhat.com>
  namespace: zipship
  description: "Example of a podman driver, runs locally not in devspaces (yet)"
  company: "Red Hat"

  license: "GPL-3.0-or-later"

  min_ansible_version: "2.14"

  platforms:
    - name: Fedora
      versions:
        - '37'
    - name: EL
      versions:
        - '8'

galaxy_tags: []

dependencies: []
